/**
 * Export helper utilities for converting rendered artifacts to browser formats
 */

import type {
  QuillmarkEngine,
  RenderOptions,
  RenderResult,
  RenderFormat,
  QuillInfo,
  ParsedDocument
} from './types';

/** Time to wait before revoking blob URLs (in milliseconds) */
const BLOB_URL_REVOKE_DELAY = 1500;

/**
 * Format configuration (Cascade 5 pattern)
 *
 * Centralized configuration for each supported format.
 * Eliminates duplicate MIME type strings and format-specific logic.
 */
interface FormatConfig {
  mimeType: string;
  extension: string;
  render: (bytes: Uint8Array, element: HTMLElement) => void;
}

const FORMAT_CONFIG: Record<RenderFormat, FormatConfig> = {
  pdf: {
    mimeType: 'application/pdf',
    extension: '.pdf',
    render: (bytes: Uint8Array, element: HTMLElement) => {
      // Create blob URL and embed for PDF viewing
      const blob = new Blob([bytes as BlobPart], { type: 'application/pdf' });
      const url = URL.createObjectURL(blob);
      const embed = document.createElement('embed');
      embed.src = url;
      embed.type = 'application/pdf';
      embed.width = '100%';
      embed.height = '600px';
      element.appendChild(embed);
    }
  },
  svg: {
    mimeType: 'image/svg+xml',
    extension: '.svg',
    render: (bytes: Uint8Array, element: HTMLElement) => {
      // Inject SVG directly for best preview experience
      // Note: SVG is generated by the Quillmark engine (trusted source)
      element.innerHTML = new TextDecoder().decode(bytes);
    }
  }
} as const;

/**
 * Normalize legacy WASM output to standardized RenderResult format
 *
 * This function handles the 10+ different artifact formats that WASM might return
 * and converts them to the standard { main: Uint8Array } format.
 *
 * @internal
 */
function normalizeWasmResult(rawResult: any): RenderResult {
  const outputFormat = rawResult.outputFormat || 'svg';

  // Helper to convert any byte format to Uint8Array
  const toUint8Array = (bytesOrArtifact: any): Uint8Array => {
    if (bytesOrArtifact == null) return new Uint8Array(0);

    // Unwrap { bytes: ... } wrapper objects
    if (typeof bytesOrArtifact === 'object' && 'bytes' in bytesOrArtifact) {
      return toUint8Array(bytesOrArtifact.bytes);
    }

    // Handle Uint8Array (already correct format)
    if (bytesOrArtifact instanceof Uint8Array) {
      return bytesOrArtifact;
    }

    // Handle ArrayBuffer
    if (bytesOrArtifact instanceof ArrayBuffer) {
      return new Uint8Array(bytesOrArtifact);
    }

    // Handle plain arrays
    if (Array.isArray(bytesOrArtifact)) {
      return new Uint8Array(bytesOrArtifact);
    }

    // Handle strings (with base64 detection)
    if (typeof bytesOrArtifact === 'string') {
      const compact = bytesOrArtifact.replace(/\s+/g, '');
      const isBase64 = /^[A-Za-z0-9+/]+=*$/.test(compact) && compact.length % 4 === 0;
      if (isBase64) {
        const binary = atob(compact);
        const out = new Uint8Array(binary.length);
        for (let i = 0; i < binary.length; i++) out[i] = binary.charCodeAt(i);
        return out;
      }
      return new TextEncoder().encode(bytesOrArtifact);
    }

    // Handle iterables
    try {
      const maybeArray = Array.from(bytesOrArtifact as any) as number[];
      return new Uint8Array(maybeArray);
    } catch (e) {
      throw new Error('Unsupported artifact bytes type: ' + Object.prototype.toString.call(bytesOrArtifact));
    }
  };

  // Extract artifacts - preserve the natural structure from WASM
  let artifacts: Uint8Array | Uint8Array[] | Record<string, Uint8Array>;

  if (Array.isArray(rawResult.artifacts)) {
    // Array format: multiple pages/artifacts
    if (rawResult.artifacts.length === 0) {
      artifacts = new Uint8Array(0);
    } else if (rawResult.artifacts.length === 1) {
      artifacts = toUint8Array(rawResult.artifacts[0]);
    } else {
      artifacts = rawResult.artifacts.map(toUint8Array);
    }
  } else if (rawResult.artifacts && typeof rawResult.artifacts === 'object') {
    // Object format: named artifacts (e.g., { main: ..., header: ... })
    // Preserve all keys from the object
    const obj: Record<string, Uint8Array> = {};
    for (const [key, value] of Object.entries(rawResult.artifacts)) {
      obj[key] = toUint8Array(value);
    }
    // If it's a single 'main' artifact, unwrap it
    const keys = Object.keys(obj);
    if (keys.length === 1 && keys[0] === 'main') {
      artifacts = obj.main;
    } else {
      artifacts = obj;
    }
  } else if (rawResult.artifacts) {
    // Direct format: single artifact
    artifacts = toUint8Array(rawResult.artifacts);
  } else {
    artifacts = new Uint8Array(0);
  }

  // Return standardized format
  return {
    artifacts,
    outputFormat
  };
}

/**
 * Determine the preferred format for preview based on QuillInfo
 * @internal
 */
function getPreferredPreviewFormat(
  engine: QuillmarkEngine,
  quillName?: string,
  userFormat?: RenderFormat
): RenderFormat {
  // User explicitly specified a format
  if (userFormat) {
    return userFormat;
  }

  // If we can determine the quill, check its supported formats
  if (quillName) {
    try {
      const info: QuillInfo = engine.getQuillInfo(quillName);
      // Prefer SVG, fall back to PDF
      if (info.supportedFormats.includes('svg')) {
        return 'svg';
      }
      if (info.supportedFormats.includes('pdf')) {
        return 'pdf';
      }
    } catch (e) {
      // Quill not found or error getting info, fall through to default
    }
  }

  // Default: SVG
  return 'svg';
}

// ============================================================================
// NEW API - Cleaner and more semantically consistent
// ============================================================================

/**
 * Render a parsed document to a result that can be converted to various formats.
 * 
 * This is the core rendering function. It takes a pre-parsed document, determines
 * the quill to use, and renders it. The returned RenderResult
 * can be passed to conversion functions like toBlob(), toDataUrl(), etc.
 * 
 * @param engine - Quillmark engine instance (implements QuillmarkEngine interface)
 * @param parsed - Pre-parsed document from Quillmark.parseMarkdown()
 * @param options - Render options (format, quillName, assets)
 * @returns RenderResult containing artifacts and output format
 * 
 * @example
 * // Parse and render to PDF
 * import { Quillmark } from '@quillmark-test/wasm';
 * import { exporters } from '@quillmark-test/web';
 * 
 * const parsed = Quillmark.parseMarkdown(markdown);
 * const result = exporters.render(engine, parsed, { format: 'pdf' });
 * const blob = exporters.toBlob(result);
 * 
 * @example
 * // Render once, export many times
 * const parsed = Quillmark.parseMarkdown(markdown);
 * const result = exporters.render(engine, parsed, { format: 'svg' });
 * const blob = exporters.toBlob(result);
 * const dataUrl = await exporters.toDataUrl(result);
 * exporters.download(result, 'document.svg');
 */
export function render(
  engine: QuillmarkEngine,
  parsed: ParsedDocument,
  options?: RenderOptions
): RenderResult {
  const quillName = options?.quillName || parsed.quillTag;

  // Determine format (with smart default for preview)
  const format = options?.format || getPreferredPreviewFormat(engine, quillName);

  // Render using the WASM engine (returns legacy format)
  const rawResult: any = engine.render(parsed, {
    format,
    ...options
  });

  // Normalize to standard format - this is where the cascade happens!
  // We handle all 10+ legacy formats here and convert to { main: Uint8Array }
  return normalizeWasmResult(rawResult);
}

/**
 * Convert a render result to a Blob.
 *
 * For multi-page results, only the first page/artifact is converted.
 *
 * @param result - RenderResult from render()
 * @returns Blob containing the rendered output
 *
 * @example
 * const parsed = Quillmark.parseMarkdown(markdown);
 * const result = exporters.render(engine, parsed, { format: 'pdf' });
 * const blob = exporters.toBlob(result);
 * const url = URL.createObjectURL(blob);
 */
export function toBlob(result: RenderResult): Blob {
  const config = FORMAT_CONFIG[result.outputFormat];
  const bytes = Array.isArray(result.artifacts)
    ? result.artifacts[0]
    : (result.artifacts instanceof Uint8Array ? result.artifacts : result.artifacts.main);
  return new Blob([bytes as BlobPart], { type: config.mimeType });
}

/**
 * Convert a render result to a data URL.
 *
 * @param result - RenderResult from render()
 * @returns Promise resolving to data URL string
 *
 * @example
 * const parsed = Quillmark.parseMarkdown(markdown);
 * const result = exporters.render(engine, parsed, { format: 'svg' });
 * const dataUrl = await exporters.toDataUrl(result);
 * imgElement.src = dataUrl;
 */
export async function toDataUrl(result: RenderResult): Promise<string> {
  const blob = toBlob(result);
  
  // Check if we're in a browser environment with FileReader
  if (typeof FileReader !== 'undefined') {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  }
  
  // Node.js environment fallback using Buffer
  if (typeof Buffer !== 'undefined') {
    const arrayBuffer = await blob.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);
    const base64 = buffer.toString('base64');
    return `data:${blob.type};base64,${base64}`;
  }
  
  // Fallback for environments without FileReader or Buffer
  throw new Error('toDataUrl requires either FileReader (browser) or Buffer (Node.js) to be available');
}

/**
 * Display a render result in a DOM element.
 *
 * Intelligently handles different formats using the format configuration.
 * - SVG: Injects directly into element
 * - PDF: Creates an embed element
 *
 * For multi-page results (arrays), renders all pages vertically in a scrollable container.
 *
 * Note: SVG content is rendered as-is. If the SVG source is untrusted,
 * consider sanitizing it before rendering to prevent XSS attacks.
 *
 * @param result - RenderResult from render()
 * @param element - Target HTML element
 *
 * @example
 * const parsed = Quillmark.parseMarkdown(markdown);
 * const result = exporters.render(engine, parsed, { format: 'svg' });
 * const preview = document.getElementById('preview');
 * exporters.toElement(result, preview);
 */
export function toElement(
  result: RenderResult,
  element: HTMLElement
): void {
  const config = FORMAT_CONFIG[result.outputFormat];

  // Clear existing content
  element.innerHTML = '';

  if (Array.isArray(result.artifacts)) {
    // Multiple pages - render all in separate containers, stacked vertically
    result.artifacts.forEach((artifact, index) => {
      const pageContainer = document.createElement('div');
      pageContainer.className = 'page';
      pageContainer.style.marginBottom = '20px';
      pageContainer.style.borderBottom = '1px solid #e0e0e0';
      pageContainer.style.paddingBottom = '20px';
      pageContainer.style.clear = 'both';

      // Add page number
      const pageLabel = document.createElement('div');
      pageLabel.textContent = `Page ${index + 1}`;
      pageLabel.style.fontSize = '12px';
      pageLabel.style.color = '#757575';
      pageLabel.style.marginBottom = '10px';
      pageContainer.appendChild(pageLabel);

      const contentContainer = document.createElement('div');
      config.render(artifact, contentContainer);

      pageContainer.appendChild(contentContainer);
      element.appendChild(pageContainer);
    });
  } else {
    // Single page (Uint8Array or object with named artifacts)
    const bytes = result.artifacts instanceof Uint8Array
      ? result.artifacts
      : result.artifacts.main;
    config.render(bytes, element);
  }
}

/**
 * Download a render result as a file.
 *
 * Triggers a browser download with the appropriate MIME type.
 *
 * @param result - RenderResult from render()
 * @param filename - Name for the downloaded file
 *
 * @example
 * const parsed = Quillmark.parseMarkdown(markdown);
 * const result = exporters.render(engine, parsed, { format: 'pdf' });
 * exporters.download(result, 'document.pdf');
 */
export function download(
  result: RenderResult,
  filename: string
): void {
  const blob = toBlob(result);

  // Trigger browser download
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), BLOB_URL_REVOKE_DELAY);
}

/**
 * Convert render result artifacts to strings.
 *
 * Decodes artifact(s) to UTF-8 strings. This is particularly useful for SVG output.
 *
 * - Single artifact: Returns the string directly
 * - Multiple artifacts (array): Returns an array of strings
 * - Named artifacts (object): Returns an object with string values
 *
 * @param result - RenderResult from render()
 * @returns String, array of strings, or object with string values
 *
 * @example
 * // Single page
 * const parsed = Quillmark.parseMarkdown(markdown);
 * const result = exporters.render(engine, parsed, { format: 'svg' });
 * const svg = exporters.toString(result);
 * // svg is '<svg>...</svg>'
 *
 * @example
 * // Multiple pages (array)
 * const parsed = Quillmark.parseMarkdown(longMarkdown);
 * const result = exporters.render(engine, parsed, { format: 'svg' });
 * const pages = exporters.toString(result);
 * // pages is ['<svg>page 1</svg>', '<svg>page 2</svg>', ...]
 *
 * @example
 * // Named artifacts (object)
 * const parsed = Quillmark.parseMarkdown(markdown);
 * const result = exporters.render(engine, parsed, { format: 'svg' });
 * const parts = exporters.toString(result);
 * // parts is { main: '<svg>...</svg>', header: '<svg>...</svg>' }
 *
 * @example
 * // Send to server
 * const parsed = Quillmark.parseMarkdown(markdown);
 * const result = exporters.render(engine, parsed, { format: 'svg' });
 * const data = exporters.toString(result);
 * await fetch('/api/save', {
 *   method: 'POST',
 *   body: JSON.stringify({ data })
 * });
 */
export function toString(result: RenderResult): string | string[] | Record<string, string> {
  if (result.artifacts instanceof Uint8Array) {
    // Single artifact
    return new TextDecoder().decode(result.artifacts);
  } else if (Array.isArray(result.artifacts)) {
    // Multiple artifacts as array
    return result.artifacts.map(artifact => new TextDecoder().decode(artifact));
  } else {
    // Named artifacts as object
    const strings: Record<string, string> = {};
    for (const [key, artifact] of Object.entries(result.artifacts)) {
      strings[key] = new TextDecoder().decode(artifact);
    }
    return strings;
  }
}



