/**
 * Export helper utilities for converting rendered artifacts to browser formats
 */

import { Quillmark } from '@quillmark-test/wasm';
import type {
  RenderOptions,
  RenderResult,
  RenderFormat,
  QuillInfo,
  ParsedDocument
} from './types';

/** Time to wait before revoking blob URLs (in milliseconds) */
const BLOB_URL_REVOKE_DELAY = 1500;

/**
 * Format configuration (Cascade 5 pattern)
 *
 * Centralized configuration for each supported format.
 * Eliminates duplicate MIME type strings and format-specific logic.
 */
interface FormatConfig {
  mimeType: string;
  extension: string;
  render: (bytes: Uint8Array, element: HTMLElement) => void;
}

const FORMAT_CONFIG: Record<RenderFormat, FormatConfig> = {
  pdf: {
    mimeType: 'application/pdf',
    extension: '.pdf',
    render: (bytes: Uint8Array, element: HTMLElement) => {
      // Create blob URL and embed for PDF viewing
      const blob = new Blob([bytes], { type: 'application/pdf' });
      const url = URL.createObjectURL(blob);
      const embed = document.createElement('embed');
      embed.src = url;
      embed.type = 'application/pdf';
      embed.width = '100%';
      embed.height = '600px';
      element.appendChild(embed);
    }
  },
  svg: {
    mimeType: 'image/svg+xml',
    extension: '.svg',
    render: (bytes: Uint8Array, element: HTMLElement) => {
      // Inject SVG directly for best preview experience
      // Note: SVG is generated by the Quillmark engine (trusted source)
      element.innerHTML = new TextDecoder().decode(bytes);
    }
  }
} as const;

/**
 * Normalize legacy WASM output to standardized RenderResult format
 *
 * This function handles the 10+ different artifact formats that WASM might return
 * and converts them to the standard { main: Uint8Array } format.
 *
 * @internal
 */
function normalizeWasmResult(rawResult: any): RenderResult {
  const outputFormat = rawResult.outputFormat || 'svg';

  // Helper to convert any byte format to Uint8Array
  const toUint8Array = (bytesOrArtifact: any): Uint8Array => {
    if (bytesOrArtifact == null) return new Uint8Array(0);

    // Unwrap { bytes: ... } wrapper objects
    if (typeof bytesOrArtifact === 'object' && 'bytes' in bytesOrArtifact) {
      return toUint8Array(bytesOrArtifact.bytes);
    }

    // Handle Uint8Array (already correct format)
    if (bytesOrArtifact instanceof Uint8Array) {
      return bytesOrArtifact;
    }

    // Handle ArrayBuffer
    if (bytesOrArtifact instanceof ArrayBuffer) {
      return new Uint8Array(bytesOrArtifact);
    }

    // Handle plain arrays
    if (Array.isArray(bytesOrArtifact)) {
      return new Uint8Array(bytesOrArtifact);
    }

    // Handle strings (with base64 detection)
    if (typeof bytesOrArtifact === 'string') {
      const compact = bytesOrArtifact.replace(/\s+/g, '');
      const isBase64 = /^[A-Za-z0-9+/]+=*$/.test(compact) && compact.length % 4 === 0;
      if (isBase64) {
        const binary = atob(compact);
        const out = new Uint8Array(binary.length);
        for (let i = 0; i < binary.length; i++) out[i] = binary.charCodeAt(i);
        return out;
      }
      return new TextEncoder().encode(bytesOrArtifact);
    }

    // Handle iterables
    try {
      const maybeArray = Array.from(bytesOrArtifact as any) as number[];
      return new Uint8Array(maybeArray);
    } catch (e) {
      throw new Error('Unsupported artifact bytes type: ' + Object.prototype.toString.call(bytesOrArtifact));
    }
  };

  // Extract main artifact from various structural formats
  let mainArtifact: Uint8Array;

  if (Array.isArray(rawResult.artifacts)) {
    // Array format: result.artifacts[0]
    mainArtifact = toUint8Array(rawResult.artifacts[0]);
  } else if (rawResult.artifacts && typeof rawResult.artifacts === 'object' && 'main' in rawResult.artifacts) {
    // Object format: result.artifacts.main (already standardized!)
    mainArtifact = toUint8Array(rawResult.artifacts.main);
  } else if (rawResult.artifacts) {
    // Direct format: result.artifacts
    mainArtifact = toUint8Array(rawResult.artifacts);
  } else {
    mainArtifact = new Uint8Array(0);
  }

  // Return standardized format
  return {
    artifacts: {
      main: mainArtifact
    },
    outputFormat
  };
}

/**
 * Determine the preferred format for preview based on QuillInfo
 * @internal
 */
function getPreferredPreviewFormat(
  engine: Quillmark,
  quillName?: string,
  userFormat?: RenderFormat
): RenderFormat {
  // User explicitly specified a format
  if (userFormat) {
    return userFormat;
  }

  // If we can determine the quill, check its supported formats
  if (quillName) {
    try {
      const info: QuillInfo = engine.getQuillInfo(quillName);
      // Prefer SVG, fall back to PDF
      if (info.supportedFormats.includes('svg')) {
        return 'svg';
      }
      if (info.supportedFormats.includes('pdf')) {
        return 'pdf';
      }
    } catch (e) {
      // Quill not found or error getting info, fall through to default
    }
  }

  // Default: SVG
  return 'svg';
}

// ============================================================================
// NEW API - Cleaner and more semantically consistent
// ============================================================================

/**
 * Render markdown to a result that can be converted to various formats.
 * 
 * This is the core rendering function. It parses the markdown, determines
 * the quill to use, and renders the document. The returned RenderResult
 * can be passed to conversion functions like toBlob(), toDataUrl(), etc.
 * 
 * @param engine - Quillmark engine instance
 * @param markdown - Markdown content to render
 * @param options - Render options (format, quillName, assets)
 * @returns RenderResult containing artifacts and output format
 * 
 * @example
 * // Render to PDF
 * const result = render(engine, markdown, { format: 'pdf' });
 * const blob = toBlob(result);
 * 
 * @example
 * // Render once, export many times
 * const result = render(engine, markdown, { format: 'svg' });
 * const blob = toBlob(result);
 * const dataUrl = await toDataUrl(result);
 * download(result, 'document.svg');
 */
export function render(
  engine: Quillmark,
  markdown: string,
  options?: RenderOptions
): RenderResult {
  // Parse markdown to get quill tag and fields
  const parsed: ParsedDocument = Quillmark.parseMarkdown(markdown);
  const quillName = options?.quillName || parsed.quillTag;

  // Determine format (with smart default for preview)
  const format = options?.format || getPreferredPreviewFormat(engine, quillName);

  // Render using the WASM engine (returns legacy format)
  const rawResult: any = engine.render(parsed, {
    format,
    ...options
  });

  // Normalize to standard format - this is where the cascade happens!
  // We handle all 10+ legacy formats here and convert to { main: Uint8Array }
  return normalizeWasmResult(rawResult);
}

/**
 * Convert a render result to an SVG string.
 *
 * This is the primary use case for SVG output - getting the string content
 * to inject into your own widgets, components, or applications.
 *
 * @param result - RenderResult from render() (must be SVG format)
 * @returns Decoded SVG string
 * @throws Error if result is not SVG format
 *
 * @example
 * const result = render(engine, markdown, { format: 'svg' });
 * const svgString = toSvg(result);
 * myCustomWidget.innerHTML = svgString;
 */
export function toSvg(result: RenderResult): string {
  if (result.outputFormat !== 'svg') {
    throw new Error(`toSvg() requires SVG format, got: ${result.outputFormat}`);
  }
  return new TextDecoder().decode(result.artifacts.main);
}

/**
 * Convert a render result to a Blob.
 *
 * @param result - RenderResult from render()
 * @returns Blob containing the rendered output
 *
 * @example
 * const result = render(engine, markdown, { format: 'pdf' });
 * const blob = toBlob(result);
 * const url = URL.createObjectURL(blob);
 */
export function toBlob(result: RenderResult): Blob {
  const config = FORMAT_CONFIG[result.outputFormat];
  return new Blob([result.artifacts.main], { type: config.mimeType });
}

/**
 * Convert a render result to a data URL.
 *
 * @param result - RenderResult from render()
 * @returns Promise resolving to data URL string
 *
 * @example
 * const result = render(engine, markdown, { format: 'svg' });
 * const dataUrl = await toDataUrl(result);
 * imgElement.src = dataUrl;
 */
export async function toDataUrl(result: RenderResult): Promise<string> {
  const blob = toBlob(result);
  
  // Check if we're in a browser environment with FileReader
  if (typeof FileReader !== 'undefined') {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  }
  
  // Node.js environment fallback using Buffer
  if (typeof Buffer !== 'undefined') {
    const arrayBuffer = await blob.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);
    const base64 = buffer.toString('base64');
    return `data:${blob.type};base64,${base64}`;
  }
  
  // Fallback for environments without FileReader or Buffer
  throw new Error('toDataUrl requires either FileReader (browser) or Buffer (Node.js) to be available');
}

/**
 * Display a render result in a DOM element.
 *
 * Intelligently handles different formats using the format configuration.
 * - SVG: Injects directly into element
 * - PDF: Creates an embed element
 *
 * Note: SVG content is rendered as-is. If the SVG source is untrusted,
 * consider sanitizing it before rendering to prevent XSS attacks.
 *
 * @param result - RenderResult from render()
 * @param element - Target HTML element
 *
 * @example
 * const result = render(engine, markdown, { format: 'svg' });
 * const preview = document.getElementById('preview');
 * toElement(result, preview);
 */
export function toElement(
  result: RenderResult,
  element: HTMLElement
): void {
  const config = FORMAT_CONFIG[result.outputFormat];

  // Clear existing content
  element.innerHTML = '';

  // Use format-specific render function (Cascade 5 pattern)
  config.render(result.artifacts.main, element);
}

/**
 * Download a render result as a file.
 *
 * Triggers a browser download with the appropriate MIME type.
 *
 * @param result - RenderResult from render()
 * @param filename - Name for the downloaded file
 *
 * @example
 * const result = render(engine, markdown, { format: 'pdf' });
 * download(result, 'document.pdf');
 */
export function download(
  result: RenderResult,
  filename: string
): void {
  const blob = toBlob(result);
  
  // Trigger browser download
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), BLOB_URL_REVOKE_DELAY);
}



