name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    name: Test and Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Type check
      run: npx tsc --noEmit
    
    - name: Build library
      run: npm run build:lib
    
    - name: Build playground
      run: npm run build:playground
    
    - name: Upload library artifacts
      uses: actions/upload-artifact@v4
      with:
        name: library-dist
        path: |
          dist/*.js
          dist/*.cjs
          dist/*.d.ts
          dist/*.map
        retention-days: 7
    
    - name: Upload playground artifacts
      uses: actions/upload-artifact@v4
      with:
        name: playground-dist
        path: dist/playground/
        retention-days: 7
